---
title: "Lab 12"
author: "Tan Nguyen"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include = FALSE}
# Load required libraries
library(tidyverse)
library(plotly)
library(crosstalk)

# Load the dataset
pokemon <- read_csv("pokemon.csv")

# Reorder Type 1 by median Total
pokemon <- pokemon %>%
  mutate(`Type 1` = fct_reorder(`Type 1`, Total, .fun = median, .desc = TRUE))

# Convert to SharedData for crosstalk interactivity
shared_pokemon <- SharedData$new(pokemon)
```
## SidebarName {.sidebar}
```{r}
filter_select("poke_type", "Pokemon Type", shared_pokemon, ~`Type 1`)
```

Column
-------------------------------------

### Total Stats by Pokémon Type Boxplot by Tan Nguyen

```{r, echo = FALSE}
# Construct the boxplot
p1 <- ggplot(shared_pokemon, aes(x = `Type 1`, y = Total, fill = `Type 1`)) +
  geom_boxplot() +
  labs(
    x = "Primary Type",
    y = "Total Stat"
  )  +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Conversion to interactive plotly
ggplotly(p1)
```

Column
-------------------------------------

### Attack vs Defense Scatterplot by Tan Nguyen

```{r}
p2 <- ggplot(shared_pokemon, aes(x = Defense, y = Attack, color = `Type 1`)) +
  geom_point() +
  labs(
    title = "Attack vs Defense",
    x = "Defense",
    y = "Attack",
    color = "Type"
  ) +
  theme_minimal()

ggplotly(p2)
```
